// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrganoPlenoApp.Models;

namespace OrganoPlenoApp.Migrations
{
    [DbContext(typeof(OrganContext))]
    partial class OrganContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OrganoPlenoApp.Models.Console", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Made");

                    b.Property<string>("Name");

                    b.Property<int>("OrganID");

                    b.HasKey("ID");

                    b.HasIndex("OrganID");

                    b.ToTable("Console");
                });

            modelBuilder.Entity("OrganoPlenoApp.Models.Division", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("OrganID");

                    b.HasKey("ID");

                    b.HasIndex("OrganID");

                    b.ToTable("Division");
                });

            modelBuilder.Entity("OrganoPlenoApp.Models.Organ", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Organ");
                });

            modelBuilder.Entity("OrganoPlenoApp.Models.Pipe", b =>
                {
                    b.Property<int>("ID");

                    b.Property<int>("Category");

                    b.Property<int>("DivisionID");

                    b.Property<int>("Material");

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.Property<int>("Specification");

                    b.Property<int>("Year");

                    b.HasKey("ID");

                    b.HasIndex("DivisionID");

                    b.ToTable("Pipe");
                });

            modelBuilder.Entity("OrganoPlenoApp.Models.Console", b =>
                {
                    b.HasOne("OrganoPlenoApp.Models.Organ", "Organ")
                        .WithMany("Console")
                        .HasForeignKey("OrganID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("OrganoPlenoApp.Models.Division", b =>
                {
                    b.HasOne("OrganoPlenoApp.Models.Organ", "Organ")
                        .WithMany("Divisions")
                        .HasForeignKey("OrganID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("OrganoPlenoApp.Models.Pipe", b =>
                {
                    b.HasOne("OrganoPlenoApp.Models.Division", "Division")
                        .WithMany("Pipes")
                        .HasForeignKey("DivisionID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
